// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB69h6GytYwoZ3LPJSK4Se3eIjmOMj2adI',
    appId: '1:422409304827:web:64d43fa8a00d4bd3980e5e',
    messagingSenderId: '422409304827',
    projectId: 'chat-app-d3cd9',
    authDomain: 'chat-app-d3cd9.firebaseapp.com',
    storageBucket: 'chat-app-d3cd9.firebasestorage.app',
    measurementId: 'G-T9NQR01ZGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQeRjcQiiaT1KZPgmCplDV4l9xBwXt60I',
    appId: '1:422409304827:android:86b6e2891cd99090980e5e',
    messagingSenderId: '422409304827',
    projectId: 'chat-app-d3cd9',
    storageBucket: 'chat-app-d3cd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzvD6y7vogHTo2il9_EUB2tj_wF5_WzwI',
    appId: '1:422409304827:ios:b40f4f15fe2f2978980e5e',
    messagingSenderId: '422409304827',
    projectId: 'chat-app-d3cd9',
    storageBucket: 'chat-app-d3cd9.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzvD6y7vogHTo2il9_EUB2tj_wF5_WzwI',
    appId: '1:422409304827:ios:b40f4f15fe2f2978980e5e',
    messagingSenderId: '422409304827',
    projectId: 'chat-app-d3cd9',
    storageBucket: 'chat-app-d3cd9.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB69h6GytYwoZ3LPJSK4Se3eIjmOMj2adI',
    appId: '1:422409304827:web:63bebb40e483a95e980e5e',
    messagingSenderId: '422409304827',
    projectId: 'chat-app-d3cd9',
    authDomain: 'chat-app-d3cd9.firebaseapp.com',
    storageBucket: 'chat-app-d3cd9.firebasestorage.app',
    measurementId: 'G-80Y438GLCV',
  );
}
